name: Deploy VPN Bot

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preflight – check required secrets
        run: |
          [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ] || { echo "❌ SSH_PRIVATE_KEY is empty"; exit 1; }
          [ -n "${{ secrets.SERVER_HOST }}" ] || { echo "❌ SERVER_HOST is empty"; exit 1; }
          [ -n "${{ secrets.SERVER_USER }}" ] || { echo "❌ SERVER_USER is empty"; exit 1; }
          [ -n "${{ secrets.SUDO_PASSWORD }}" ] || { echo "❌ SUDO_PASSWORD is empty"; exit 1; }
          [ -n "${{ secrets.TELEGRAM_TOKEN }}" ] || { echo "❌ TELEGRAM_TOKEN is empty"; exit 1; }

      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          printf '%s' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

      - name: Upload code to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "."
          target: "/home/${{ secrets.SERVER_USER }}/apps/simple_vpn_bot"
          overwrite: true
          rm: false


      - name: Create/merge .env and data dir (remote)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -Eeuo pipefail
            sudo -n install -d -m 755 /etc/vpn-bot
            sudo -n install -d -o bot -g bot /home/bot/data

            # якщо ~/.env є — переміщуємо, якщо ні — лишаємо старий /etc/vpn-bot/.env
            if [ -f ~/.env ]; then
              sudo -n mv -f ~/.env /etc/vpn-bot/.env
              sudo -n chown root:root /etc/vpn-bot/.env
              sudo -n chmod 0644 /etc/vpn-bot/.env
            else
              echo "[WARN] ~/.env not found, keeping existing /etc/vpn-bot/.env"
            fi

      - name: Build .env locally
        run: |
          cat > .env <<EOF
          TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          WG_INTERFACE=${{ vars.WG_INTERFACE }}
          WG_NETWORK=${{ vars.WG_NETWORK }}
          WG_ENDPOINT_HOST=${{ vars.WG_ENDPOINT_HOST }}
          WG_ENDPOINT_PORT=${{ vars.WG_ENDPOINT_PORT }}
          WG_DNS=${{ vars.WG_DNS }}
          WG_KEEPALIVE=${{ vars.WG_KEEPALIVE }}
          WG_MTU=${{ vars.WG_MTU }}
          EOF
          ls -l .env && sed -n '1,120p' .env

      - name: Copy .env to server home
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: ".env"
          target: "/home/${{ secrets.SERVER_USER }}/"
          overwrite: true


      - name: Install deps in venv (remote)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -Eeuo pipefail
            cd "/home/${{ secrets.SERVER_USER }}/apps/simple_vpn_bot"
            python3 -m venv .venv || true
            . .venv/bin/activate
            python -m pip install --upgrade pip wheel
            [ -f requirements.txt ] && pip install -r requirements.txt || true

      - name: Install/refresh systemd unit (remote)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -Eeuo pipefail
            PW="${{ secrets.SUDO_PASSWORD }}"
            run(){ printf %s\\n "$PW" | sudo -S -p "" "$@"; }

            run tee /etc/systemd/system/vpn-bot.service >/dev/null <<'UNIT'
            [Unit]
            Description=Simple VPN Telegram Bot
            After=wg-quick@wg0.service network-online.target
            Wants=wg-quick@wg0.service network-online.target

            [Service]
            User=${{ secrets.SERVER_USER }}
            WorkingDirectory=/home/${{ secrets.SERVER_USER }}/apps/simple_vpn_bot
            EnvironmentFile=/etc/vpn-bot/.env
            ExecStart=/home/${{ secrets.SERVER_USER }}/apps/simple_vpn_bot/.venv/bin/python /home/${{ secrets.SERVER_USER }}/apps/simple_vpn_bot/bot.py
            Restart=on-failure
            RestartSec=5s

            [Install]
            WantedBy=multi-user.target
            UNIT

            run install -d /etc/systemd/system/vpn-bot.service.d
            run tee /etc/systemd/system/vpn-bot.service.d/override.conf >/dev/null <<'OVR'
            [Service]
            ExecStartPre=/bin/sh -c 'for i in $(seq 1 10); do ip -4 addr show wg0 | grep -q "inet " && exit 0; sleep 1; done; echo "wg0 has no IPv4, failing"; exit 1'
            OVR

            run systemctl daemon-reload
            run systemctl enable vpn-bot.service

      - name: Restart and healthcheck (remote)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -Eeuo pipefail
            PW="${{ secrets.SUDO_PASSWORD }}"
            run(){ printf %s\\n "$PW" | sudo -S -p "" "$@"; }

            run systemctl restart vpn-bot.service
            sleep 2
            systemctl is-active --quiet vpn-bot.service
            run /usr/bin/wg show wg0 public-key >/dev/null || true
            journalctl -u vpn-bot.service -n 20 --no-pager || true
